// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbRExoQ2oBde6AA07gfYKF8zhSHN5xQA',
    appId: '1:72351881134:web:b77ba7f0f787b5a6d65a3f',
    messagingSenderId: '72351881134',
    projectId: 'sofia-bf802',
    authDomain: 'sofia-bf802.firebaseapp.com',
    databaseURL: 'https://sofia-bf802-default-rtdb.firebaseio.com',
    storageBucket: 'sofia-bf802.appspot.com',
    measurementId: 'G-7WE6E78R57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bt2cDxPFlXiN_qBhknAPd3m_BECxexU',
    appId: '1:72351881134:android:53abab007c7dff5bd65a3f',
    messagingSenderId: '72351881134',
    projectId: 'sofia-bf802',
    databaseURL: 'https://sofia-bf802-default-rtdb.firebaseio.com',
    storageBucket: 'sofia-bf802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmshjbelxyVXWaI5bmRiOwf7nAqZS7iIg',
    appId: '1:72351881134:ios:879e20c7c458f2d5d65a3f',
    messagingSenderId: '72351881134',
    projectId: 'sofia-bf802',
    databaseURL: 'https://sofia-bf802-default-rtdb.firebaseio.com',
    storageBucket: 'sofia-bf802.appspot.com',
    iosClientId: '72351881134-3nl7d5cpi7bij8ojfn16phjaj61lkr51.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmshjbelxyVXWaI5bmRiOwf7nAqZS7iIg',
    appId: '1:72351881134:ios:879e20c7c458f2d5d65a3f',
    messagingSenderId: '72351881134',
    projectId: 'sofia-bf802',
    databaseURL: 'https://sofia-bf802-default-rtdb.firebaseio.com',
    storageBucket: 'sofia-bf802.appspot.com',
    iosClientId: '72351881134-3nl7d5cpi7bij8ojfn16phjaj61lkr51.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
